name: deploy to github page

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build drifloon package
      run: |
        npx ng build drifloon
    - name: build the site
      run: |
        npx ng build site
    - name: deploy to page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/site/browser
