name: deploy to github page

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build drifloon package
      run: |
        npm install
        npx tsc
        cp package.json dist
    - name: build the site
      run: |
        cd site/
        npm install
        npx webpack
        cp -r assert/* dist
    - name: deploy to page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/dist
        destination_dir: drifloon
